# File Location:
# /etc/systemd/system/airflow-webserver.service

# Contents:
[Unit]
Description=Airflow webserver daemon
After=network.target postgresql@17-main.service
Wants=postgresql@17-main.service

[Service]
User=airflow_admin
Group=airflow_admin
Type=simple
Environment="AIRFLOW_HOME=/home/airflow_admin/airflow"
Environment="AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_admin:airflow@localhost:5432/airflow_db"
ExecStart=/home/airflow_admin/airflow_venv/bin/airflow webserver
Restart=on-failure
RestartSec=5s
PrivateTmp=true

[Install]
WantedBy=multi-user.target